name: GCP Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "principal://iam.googleapis.com/projects/1095252659035/locations/global/workloadIdentityPools/github-pool2/subject/SUBJECT_ATTRIBUTE_VALUE"
          service_account: "github-cicd@jialedu.iam.gserviceaccount.com"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t app .

      - name: Tag image
        run: |
          docker tag app northamerica-northeast2-docker.pkg.dev/jialedu/du-assignment3/app:latest

      - name: Push to Artifact Registry
        run: |
          docker push northamerica-northeast2-docker.pkg.dev/jialedu/du-assignment3/app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy du-cloudrun-app \
            --image=northamerica-northeast2-docker.pkg.dev/jialedu/du-assignment3/app:latest \
            --region=northamerica-northeast2 \
            --platform=managed \
            --allow-unauthenticated=false

